### ISSUE TITLE
bad request when sending message to discord

### ISSUE THREAD

**Issue by xinc** [flakas/reconbot#4]
edit

**Comment by ysm1mh** [comment]
same issue here. tried so many times. mades new bots and still nothing.
  maybe some to do with 2FA ??

**Comment by flakas** [comment]
Thanks for including logging information.
It's easier to see that the notification itself looks reasonable, isn't too long to be accepted by Discord API.

However, I'm still puzzled as to why it's happening - thus far I'm unable to reproduce the issue - with correct details and Discord set up in a straightforward way (without any required permissions) it seems to be working.

The closest hint I found in a different project is [here](https://github.com/home-assistant/home-assistant/issues/5688), where they had issues with Discord responding `HTTP 400 BAD REQUEST: Unauthorized` due to how connection was used in the app.
Will dig into it deeper.

---------------------

> maybe some to do with 2FA ??

I doubt it is. Access tokens are for the bot user, not your personal Discord account.

**Comment by xinc** [comment]
Just noticed in the logs python 3.5. This issued is solved for me using python 3.6
